# Generated by Django 4.2.7 on 2024-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0049_alter_notification_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.CharField(choices=[('Like', 'Like'), ('Blog', 'Blog'), ('Follow', 'Follow')], max_length=20),
        ),
    ]
