# Generated by Django 4.2.7 on 2024-01-19 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog_trash_banners/')),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad10',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad10_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad4',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad4_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad5',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad5_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad6',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad6_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad7',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad7_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad8',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad8_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad9',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad9_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(upload_to='blog_banners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ManyToManyField(to='blog.blog')),
            ],
        ),
    ]
