# Generated by Django 4.2.7 on 2023-12-10 14:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(upload_to=blog.models.UploadToPath('blog_banners')),
        ),
    ]
