# Generated by Django 4.2.7 on 2023-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_slug_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugv_ad',
            name='ad10',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad10_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad4',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad4_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad5',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad5_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad6',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad6_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad7',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad7_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad8',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad8_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad9',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ugv_ad',
            name='ad9_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
