# Generated by Django 4.2.7 on 2023-12-11 13:04

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_follow_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.UploadToPath('users_images')),
        ),
    ]
